services:
  app:
    build:
      target: development
    environment:
      FLASK_ENV: development
    volumes:
      - .:/app
      - venv_data:/app/.venv
      - uploads_data_dev:/app/uploads

volumes:
  venv_data:
  uploads_data_dev: