"""state uniqueconstraint in goals table

Revision ID: 4f99878da8ec
Revises: 39a6a58e6864
Create Date: 2026-07-09 23:37:29.552381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f99878da8ec'
down_revision = '39a6a58e6864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_goal_date', ['user_id', 'effective_date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_goal_date', type_='unique')

    # ### end Alembic commands ###
