"""create goals table

Revision ID: 55ba37b9aea2
Revises: 6b1e21e3bcc4
Create Date: 2026-07-05 16:15:28.430071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ba37b9aea2'
down_revision = '6b1e21e3bcc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=False),
    sa.Column('calorie_kcal', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Integer(), nullable=False),
    sa.Column('carb_g', sa.Integer(), nullable=False),
    sa.Column('fat_g', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goals')
    # ### end Alembic commands ###
