"""meals: convert integer values to numeric

Revision ID: 6febd7a71687
Revises: 4f99878da8ec
Create Date: 2026-08-08 21:46:02.627176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6febd7a71687'
down_revision = '4f99878da8ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.alter_column('calorie_kcal',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=6, scale=1),
               existing_nullable=False)
        batch_op.alter_column('protein_g',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=6, scale=1),
               existing_nullable=False)
        batch_op.alter_column('carb_g',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=6, scale=1),
               existing_nullable=False)
        batch_op.alter_column('fat_g',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=6, scale=1),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.alter_column('fat_g',
               existing_type=sa.Numeric(precision=6, scale=1),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('carb_g',
               existing_type=sa.Numeric(precision=6, scale=1),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('protein_g',
               existing_type=sa.Numeric(precision=6, scale=1),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('calorie_kcal',
               existing_type=sa.Numeric(precision=6, scale=1),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
